# Generated by Django 5.2.8 on 2026-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=160)),
                ('country_code', models.CharField(max_length=2)),
                ('timezone_name', models.CharField(default='Europe/Dublin', max_length=64)),
            ],
        ),
    ]
