# Generated by Django 4.2.16 on 2026-09-03 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('markup_bps', models.PositiveIntegerField(default=25)),
                ('users', models.ManyToManyField(related_name='fx_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
