# Generated by Django 4.2.16 on 2026-09-03 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sell_currency', models.CharField(max_length=3)),
                ('buy_currency', models.CharField(max_length=3)),
                ('sell_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
            ],
        ),
    ]
