# Generated by Django 5.2.8 on 2026-09-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('iban', models.CharField(max_length=34)),
                ('bank_country', models.CharField(max_length=2)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='customers.organisation')),
            ],
        ),
    ]
