# Generated by Django 5.2.8 on 2026-09-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=24)),
                ('remote_id', models.CharField(max_length=120)),
                ('published_at', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='content.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'channel'), name='one_publication_per_post_channel')],
            },
        ),
    ]
