# Generated by Django 5.2.8 on 2026-09-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('unwanted', 'Unwanted'), ('wrong_item', 'Wrong item')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed')], default='requested', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('receiving_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveSmallIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='orders.orderline')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnrequest')),
            ],
        ),
    ]
