# Generated by Django 5.2.8 on 2026-09-03 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customers.organisation')),
            ],
        ),
    ]
