# Generated by Django 4.2.16 on 2026-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('observed_at', models.DateTimeField()),
                ('provider', models.CharField(default='primary', max_length=40)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
    ]
