# Generated by Django 5.2.8 on 2026-09-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=24)),
                ('label_id', models.CharField(max_length=100)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='returns.returnrequest')),
            ],
        ),
    ]
