# Generated by Django 5.2.8 on 2026-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24, unique=True)),
                ('asset_type', models.CharField(choices=[('equity', 'Equity'), ('option', 'Option'), ('future', 'Future')], max_length=12)),
                ('quote_currency', models.CharField(max_length=3)),
                ('contract_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
            ],
        ),
    ]
